repos:
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.39.1  # Use the sha / tag you want to point at
    hooks:
    -   id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
-   repo: local
    hooks:
    -   id: prettier
        name: prettier
        entry: bunx prettier --write
        language: system
        types_or: [javascript, jsx, ts, tsx, json, markdown]
-   repo: local
    hooks:
    -   id: crossword-thumbnail
        name: crossword-thumbnail
        entry: thumbnail_generation/crosswords/generate.sh
        language: system
        files: '\.crossword\.json$'
